/**
 * ATS Scoring Logic
 * Calculates ATS compatibility score based on resume and job analysis
 */

export function calculateATSScore(resumeData, jobAnalysis) {
    let score = 0;
    const issues = [];
    const strengths = [];

    const optimized = resumeData.optimizedResume || resumeData;

    // 1. KEYWORD MATCHING (40 points)
    const resumeText = JSON.stringify(optimized).toLowerCase();
    const criticalKeywords = (jobAnalysis.keywords?.critical || [])
        .concat(jobAnalysis.atsKeywords?.technical || []);

    const uniqueKeywords = [...new Set(criticalKeywords.map(k => k.toLowerCase()))];
    const matchedKeywords = uniqueKeywords.filter(kw => resumeText.includes(kw));

    const keywordScore = (matchedKeywords.length / Math.max(uniqueKeywords.length, 1)) * 40;
    score += keywordScore;

    if (matchedKeywords.length === uniqueKeywords.length) {
        strengths.push('Perfect match on critical keywords');
    } else if (matchedKeywords.length > uniqueKeywords.length * 0.7) {
        strengths.push(`Good keyword coverage (${matchedKeywords.length}/${uniqueKeywords.length})`);
    } else {
        issues.push(`Missing important keywords: ${uniqueKeywords.filter(k => !matchedKeywords.includes(k)).slice(0, 5).join(', ')}`);
    }

    // 2. FORMATTING CHECKS (20 points)
    // Since our PDF output is standardized, we give full points for structure if generated by us
    // But we allow for user edits, so we check basics
    let formatScore = 20;
    const sections = ['experiences', 'education', 'skills'];
    const hasSections = sections.every(s => optimized[s] && optimized[s].length > 0);

    if (hasSections) {
        strengths.push('Standard ATS sections present');
    } else {
        formatScore -= 10;
        issues.push('Missing main sections (Experience, Education usually required)');
    }
    score += formatScore;

    // 3. QUANTIFIED ACHIEVEMENTS (20 points)
    const achievements = optimized.experiences?.flatMap(e => e.achievements || []) || [];
    const quantified = achievements.filter(ach => {
        const text = typeof ach === 'string' ? ach : ach.text;
        return /\d+%|\$\d+|\d+ (users|clients|projects|teams)/i.test(text);
    });

    const quantRatio = achievements.length ? quantified.length / achievements.length : 0;
    const quantScore = quantRatio * 20;
    score += quantScore;

    if (quantRatio > 0.5) {
        strengths.push('Strong use of metrics and numbers');
    } else if (achievements.length > 0) {
        issues.push('Achievements lack quantification (numbers/%)');
    }

    // 4. SKILLS MATCH (20 points)
    const requiredSkills = (jobAnalysis.requiredSkills?.mustHave || [])
        .concat(jobAnalysis.requiredSkills?.technical || [])
        .map(s => s.toLowerCase());

    // Collect all user skills
    const technicalSkills = optimized.skills?.technical || {};
    const allUserSkills = [
        ...(technicalSkills.languages || []),
        ...(technicalSkills.frameworks || []),
        ...(technicalSkills.tools || []),
        ...(technicalSkills.other || []),
        ...(optimized.skills?.soft || [])
    ].map(s => s.toLowerCase());

    const matchedSkills = requiredSkills.filter(req =>
        allUserSkills.some(userSkill => userSkill.includes(req) || req.includes(userSkill))
    );

    const skillScore = (matchedSkills.length / Math.max(requiredSkills.length, 1)) * 20;
    score += skillScore;

    if (matchedSkills.length === requiredSkills.length) {
        strengths.push('Matches all required technical skills');
    } else {
        issues.push(`Missing required skills: ${requiredSkills.filter(r => !matchedSkills.includes(r)).slice(0, 3).join(', ')}`);
    }

    // Final calculation
    const totalScore = Math.min(Math.round(score), 100);
    let grade = 'F';
    if (totalScore >= 90) grade = 'A';
    else if (totalScore >= 80) grade = 'B';
    else if (totalScore >= 70) grade = 'C';
    else if (totalScore >= 60) grade = 'D';

    return {
        score: totalScore,
        grade,
        strengths,
        issues,
        summary: `Grade ${grade} - ${totalScore}/100`
    };
}
