import type { Quest, UserProfile, FriendActivity, CompletedQuest } from "@/types";

export const MOCK_QUESTS: Quest[] = [
  {
    id: "1",
    title: "Crash a swing dance social",
    description:
      "Find a local swing dancing event and just show up. Most scenes are super welcoming to beginners — you might get swept into a whole new community.",
    track: "fun",
    time_minutes: 180,
    location_type: "city",
    energy_level: 2,
    tags: ["dancing", "social", "music", "beginners welcome"],
    status: "approved",
    created_by: "admin",
    created_at: "2024-01-01",
    community_rating: 4.8,
    rating_count: 34,
  },
  {
    id: "2",
    title: "Go foraging",
    description:
      "Find a local foraging group or guided walk. Look for wild edibles like ramps, morels, or blackberries depending on the season. Go with someone experienced.",
    track: "eco",
    time_minutes: 120,
    location_type: "outdoors",
    energy_level: 2,
    tags: ["nature", "food", "outdoors", "group"],
    status: "approved",
    created_by: "admin",
    created_at: "2024-01-02",
    community_rating: 4.6,
    rating_count: 21,
  },
  {
    id: "3",
    title: "Sit in on a public court trial",
    description:
      "Courtrooms are public. Find your local courthouse schedule and just walk in. Criminal, civil, whatever — real drama, real stakes, free entry.",
    track: "fun",
    time_minutes: 90,
    location_type: "city",
    energy_level: 1,
    tags: ["civic", "solo", "weird", "free"],
    status: "approved",
    created_by: "admin",
    created_at: "2024-01-03",
    community_rating: 4.3,
    rating_count: 18,
  },
  {
    id: "4",
    title: "Volunteer at a soup kitchen",
    description:
      "Sign up for a single volunteer shift at your local food bank or soup kitchen. Takes 2-3 hours, deeply grounding, and you'll want to go back.",
    track: "health",
    time_minutes: 150,
    location_type: "city",
    energy_level: 2,
    tags: ["volunteer", "community", "meaningful"],
    status: "approved",
    created_by: "admin",
    created_at: "2024-01-04",
    community_rating: 4.9,
    rating_count: 52,
  },
  {
    id: "5",
    title: "Geocache hunt",
    description:
      "Download the Geocaching app and find your first cache. There are probably dozens hidden within a mile of you right now.",
    track: "health",
    time_minutes: 60,
    location_type: "outdoors",
    energy_level: 2,
    tags: ["outdoors", "puzzle", "solo or group", "free"],
    status: "approved",
    created_by: "admin",
    created_at: "2024-01-05",
    community_rating: 4.5,
    rating_count: 29,
  },
  {
    id: "6",
    title: "Attend an open mic night",
    description:
      "Find a local bar or coffee shop hosting an open mic. Perform if you're brave, or just sit back and watch strangers pour their hearts out.",
    track: "fun",
    time_minutes: 120,
    location_type: "city",
    energy_level: 1,
    tags: ["music", "social", "creative", "evening"],
    status: "approved",
    created_by: "admin",
    created_at: "2024-01-06",
    community_rating: 4.7,
    rating_count: 41,
  },
  {
    id: "7",
    title: "Enter a local contest",
    description:
      "Find a local contest — pie baking, chili cook-off, trivia night, photography. Enter. The barrier is almost always lower than you think.",
    track: "fun",
    time_minutes: 180,
    location_type: "city",
    energy_level: 2,
    tags: ["competition", "creative", "community"],
    status: "approved",
    created_by: "admin",
    created_at: "2024-01-07",
    community_rating: 4.4,
    rating_count: 16,
  },
  {
    id: "8",
    title: "Entertain at a nursing home",
    description:
      "Call a local nursing home and offer to come play music, do a magic trick, or just chat. It takes 10 minutes to arrange and means the world.",
    track: "health",
    time_minutes: 90,
    location_type: "city",
    energy_level: 1,
    tags: ["volunteer", "music", "social", "meaningful"],
    status: "approved",
    created_by: "admin",
    created_at: "2024-01-08",
    community_rating: 5.0,
    rating_count: 9,
  },
];

export const MOCK_USER: UserProfile = {
  id: "user-1",
  username: "charles_q",
  avatar_url: undefined,
  bio: "On a mission to do weird, wonderful things.",
  xp_total: 1240,
  xp_money: 120,
  xp_health: 380,
  xp_eco: 200,
  xp_fun: 540,
  streak_days: 7,
  badges: [
    {
      id: "b1",
      name: "First Quest",
      description: "Completed your first sidequest",
      icon: "🗺️",
      track: "fun",
      earned_at: "2024-01-10",
    },
    {
      id: "b2",
      name: "Week Streak",
      description: "7-day quest streak",
      icon: "🔥",
      track: "health",
      earned_at: "2024-01-17",
    },
    {
      id: "b3",
      name: "Eco Warrior",
      description: "Completed 5 eco quests",
      icon: "🌿",
      track: "eco",
      earned_at: "2024-01-20",
    },
  ],
  rank: "Explorer",
  created_at: "2024-01-01",
};

export const MOCK_COMPLETED: CompletedQuest[] = [
  {
    id: "cq1",
    user_id: "user-1",
    quest_id: "1",
    quest: MOCK_QUESTS[0],
    rating: 5,
    note: "Ended up staying 4 hours. Everyone was so welcoming.",
    completed_at: "2024-01-17",
    xp_earned: 120,
  },
  {
    id: "cq2",
    user_id: "user-1",
    quest_id: "5",
    quest: MOCK_QUESTS[4],
    rating: 4,
    note: "Found 3 caches. The last one was hidden in a tree knot.",
    completed_at: "2024-01-14",
    xp_earned: 80,
  },
];

export const MOCK_FRIENDS: FriendActivity[] = [
  {
    user: { ...MOCK_USER, id: "user-2", username: "alex_wilde", xp_total: 3200, rank: "Adventurer" },
    action: "completed",
    quest: MOCK_QUESTS[3],
    timestamp: "2 hours ago",
    note: "Changed my perspective on service.",
  },
  {
    user: { ...MOCK_USER, id: "user-3", username: "maya_runs", xp_total: 890, rank: "Explorer" },
    action: "wants",
    quest: MOCK_QUESTS[1],
    timestamp: "5 hours ago",
  },
  {
    user: { ...MOCK_USER, id: "user-4", username: "jordan_g", xp_total: 520, rank: "Explorer" },
    action: "completed",
    quest: MOCK_QUESTS[5],
    timestamp: "Yesterday",
    note: "Performed two songs! Hands were shaking the whole time.",
  },
  {
    user: { ...MOCK_USER, id: "user-5", username: "priya_k", xp_total: 4100, rank: "Pathfinder" },
    action: "completed",
    quest: MOCK_QUESTS[2],
    timestamp: "2 days ago",
    note: "A murder trial. I'm obsessed.",
  },
];
